# Generated by Django 3.0.7 on 2020-06-16 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_auto_20200616_0759'),
    ]

    operations = [
        migrations.AddField(
            model_name='productnutrients',
            name='nutrient_value',
            field=models.DecimalField(decimal_places=10, default=0.0, max_digits=19),
        ),
    ]
