# Generated by Django 3.0.7 on 2020-06-16 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_productnutrients_nutrient_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutrient',
            name='nutrient_name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='productnutrients',
            unique_together={('product', 'nutrient')},
        ),
    ]
